services:
  app:
    build:
      context: .
      target: final
    container_name: restaurant-order-manager-app
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: gestao_restaurante
      JWT_SECRET: 4bb7c591820bc6654219df61d4fe28adc2bc4457a5a757081af0829a5d9b5b887d96d16f39582b569878a8d0979caa1a942ce911260de0f8769a797fb458c0fb
      JWT_EXPIRES_IN: 1h
    ports:
      - 3000:3000
    depends_on:
      - db

  app-dev:
    build:
      context: .
      target: dev
    container_name: restaurant-order-manager-dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db-test
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: gestao_restaurante
      JWT_SECRET: 4bb7c591820bc6654219df61d4fe28adc2bc4457a5a757081af0829a5d9b5b887d96d16f39582b569878a8d0979caa1a942ce911260de0f8769a797fb458c0fb
      JWT_EXPIRES_IN: 1h
    ports:
      - "5500:3000"
    depends_on:
      - db-test
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gestao_restaurante
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database/initial-schema.sql:/docker-entrypoint-initdb.d/initial-schema.sql

  db-test:
    image: mysql:8
    container_name: mysql-db-test
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gestao_restaurante
    ports:
      - "3306"
    volumes:
      - db-data-test:/var/lib/mysql
      - ./database/initial-schema.sql:/docker-entrypoint-initdb.d/initial-schema.sql

volumes:
  db-data:
  db-data-test:

# secrets:
#   db-password:
#     file: db/password.txt
